apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::206499228565:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-25T12:38:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7535"
  uid: d3febf13-b7e1-42be-8b5d-069f17602b8f
data:
  mapUsers: |
    - userarn: arn:aws:iam::206499228565:user/workshop  
      username: admin
      groups:
        - system:masters
